[package]
authors = ["Pavel Ivanov <mr.pavel.ivanov@gmail.com>"]
categories = ["command-line-utilities"]
description = "Utility for viewing json-formatted log files."
keywords = ["cli", "human", "log"]
name = "hl"
version = "0.10.0-alpha.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0"
anyhow = "1"
atoi = "0"
atty = "0"
bitmask = "0"
bitflags = "1"
bytefmt = "0"
chrono = { version = "0", features = ["serde"] }
chrono-tz = { version = "0", features = ["serde"] }
closure = "0"
config = "0"
crossbeam-channel = "0"
crossbeam-queue = "0"
crossbeam-utils = "0"
derive_deref = "1"
error-chain = "0"
flate2 = "1"
heapless = "0"
htp = "0"
humantime = "2"
itertools = "0"
num_cpus = "1"
once_cell = "1"
platform-dirs = "0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
shellwords = "1"
signal-hook = "0"
structopt = "0"
thiserror = "1"
wildmatch = "2"

[dependencies.itoa]
version = "0"
default-features = false

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.winapi]
version = "0"
features = ["handleapi"]

[dev-dependencies]
criterion = "0"
stats_alloc = "0"
diligent-date-parser = "0"
regex = "1"
wildmatch = "2"

[profile.release]
debug = false
opt-level = 3
codegen-units = 1
lto = true

[[bench]]
name = "re_match"
harness = false

[[bench]]
name = "ts_parse"
harness = false

[[bench]]
name = "ts_format"
harness = false

[[bench]]
name = "wild_match"
harness = false

[[bench]]
name = "theme"
harness = false
